### PR TITLE
Fix changelog: Rm `#[doc(hidden)]`

### PR DESCRIPTION
**Pull request by NobodyXu**
Signed-off-by: Jiahao XU <Jiahao_XU@outlook.com>

### CODE REVIEW

**Comment by jonhoo** [comment]
This change is [Reviewable](https://reviewable.io/reviews/openssh-rust/openssh/90)

**Comment by NobodyXu** [comment]
@jonhoo I am going to implement #84 next, so we don't need to release a new version after merging this.

**Comment by NobodyXu** [comment]
> @jonhoo I am going to implement #84 next, so we don't need to release a new version after merging this.

That one is implemented in #91

**Review by jonhoo — APPROVED** [review]
Man, I forget about this _every_ time. Thanks!

**Pull request merged**
