### PR TITLE
Bump dep openssh-mux-client to v0.15.1

### LINKED ISSUE #98: native-mux feature can't compile anymore
Seems it depends on openssh-mux-client which depends on tokio-io-utility ^0.6.4 which has been yanked: https://crates.io/crates/tokio-io-utility/versions

A simple setup like this:
```toml
[dependencies]
openssh = { version= "0.9", default_features = false, features = ["native-mux"] }
tokio = { version = "1", default_features = false, features = ["rt-multi-thread"] }
futures = { version = "0.3", default_features = false }
```

Shows the issue:
```console
[nix-develop]$ rm Cargo.lock 
[nix-develop]$ cargo check
    Updating crates.io index
error: failed to select a version for the requirement `tokio-io-utility = "^0.6.4"`
candidate versions found which didn't match: 0.7.1
location searched: crates.io index
required by package `openssh-mux-client v0.15.0`
    ... which satisfies dependency `openssh-mux-client = "^0.15.0"` of package `openssh v0.9.0`
    ... which satisfies dependency `openssh = "^0.9"` of package `start-engine v0.1.0 (/home/shana/programming/start-engine)`
```

### PR DESCRIPTION
**Pull request by NobodyXu**
that fixed the dep on yanked tokio-io-utility v0.6.4

Fix #98 

Signed-off-by: Jiahao XU <Jiahao_XU@outlook.com>

### CODE REVIEW

**Comment by jonhoo** [comment]
This change is [Reviewable](https://reviewable.io/reviews/openssh-rust/openssh/99)

**Comment by NobodyXu** [comment]
@jonhoo Can we merge this PR and release a new minor ver ASAP since the crate currently breaks due to tokio-io-utility v0.6.4 being yanked?

**Review by jonhoo — APPROVED** [review]
This kind of change shouldn't generally be necessary. People building downstream _can_ still use newer versions of `openssh-mux-client` since 0.15.0 is compatible with 0.15.1. Why then the urgency to release this change for this crate?

**Comment by jonhoo** [comment]
Released as 0.9.7.

**Comment by jonhoo** [comment]
Ah, so, the reason you ran into trouble is because `openssh-mux-client 0.15.0` required `tokio-io-utility="0.6.4"`. When you yanked 0.6.4, and didn't release any newer version of 0.6 (and released 0.7 instead), it becomes impossible to select a version of open-ssh-mux-client without selecting a yanked version of `tokio-io-utility`, which Cargo will refuse unless you already have a lockfile selecting it.

**Comment by NobodyXu** [comment]
@jonhoo Thanks for the explanation, that was mostly an error from my part.
I will refrain from yanking unless experiencing a memory related bug and release a new minor version if yanking is necessary.

**Pull request merged**
