### PR TITLE
Refactor session builder

### PR DESCRIPTION
**Pull request by NobodyXu**
Signed-off-by: Jiahao XU <Jiahao_XU@outlook.com>

### CODE REVIEW

**Comment by jonhoo** [comment]
This change is [Reviewable](https://reviewable.io/reviews/openssh-rust/openssh/56)

**Comment by jonhoo** [comment]
Hmm, why is this better?

**Comment by NobodyXu** [comment]
> Hmm, why is this better?

It will make SessionBuilder much smaller.

**Comment by jonhoo** [comment]
But it's a builder, and for a SSH connection at that, which is already a pretty heavy-weight thing. It's size is unlikely to matter anywhere for performance, at least as far as I can see. Do you have a use-case in mind?

**Comment by NobodyXu** [comment]
> But it's a builder, and for a SSH connection at that, which is already a pretty heavy-weight thing. It's size is unlikely to matter anywhere for performance, at least as far as I can see. Do you have a use-case in mind?

Maybe for the future Windows support, where we will be connect directly without control master.

In that case, we might need to store the entire content of `SessionBuilder` in the `Session`.

**Comment by jonhoo** [comment]
If we do get to that one day, I think that's a re-organization we should do then. There's no need to do it now, and it introduces some needless complexity to the code I think.

**Comment by NobodyXu** [comment]
> If we do get to that one day, I think that's a re-organization we should do then. There's no need to do it now, and it introduces some needless complexity to the code I think.

OK, I will close this PR then,

**Pull request closed without merging**
