### PR TITLE
Add dep-autoupgrade to create PR whenever there is a new major release of any dependency

### PR DESCRIPTION
**Pull request by NobodyXu**
This PR uses [NobodyXu/dependencies-autoupdate](https://github.com/NobodyXu/dependencies-autoupdate) which is a fork.

Signed-off-by: Jiahao XU <Jiahao_XU@outlook.com>

### CODE REVIEW

**Comment by jonhoo** [comment]
This change is [Reviewable](https://reviewable.io/reviews/openssh-rust/openssh/71)

**Comment by jonhoo** [comment]
I'm not a huge fan of this — in general I prefer to combine many upgrades into one release _especially_ if they're API-visible changes that require a major bump on our side too (though we should have few of those). One alternative is to at least add a [dependency badge](https://deps.rs/repo/github/jonhoo/openssh-rs).

**Comment by NobodyXu** [comment]
> I'm not a huge fan of this — in general I prefer to combine many upgrades into one release _especially_ if they're API-visible changes that require a major bump on our side too (though we should have few of those). One alternative is to at least add a [dependency badge](https://deps.rs/repo/github/jonhoo/openssh-rs).

No, the new workflow does not automatically release this crate.

What it does is that, if one of our dependencies releases a new major version, it would create a Pull Request on this repositories so that we don't have check for new major releases ourselves.

**Comment by jonhoo** [comment]
Yep, I understand its behavior, but I think it'll still end up then being a trickle of smaller updates, and then it'll be up to us to batch them anyway. Essentially, I think it'll be mostly noise that we then have to filter out. That said, if you think it's valuable, I'm not completely opposed to trying it out.

Why are we using a fork of the tool though?

**Comment by NobodyXu** [comment]
> Yep, I understand its behavior, but I think it'll still end up then being a trickle of smaller updates, and then it'll be up to us to batch them anyway. Essentially, I think it'll be mostly noise that we then have to filter out. That said, if you think it's valuable, I'm not completely opposed to trying it out.

It only creates PR on major releases of the dependencies, so IMHO there might not be much PR opened.

One of the motivation for this CI is that we don't have to constantly watch for new major releases in our dependencies.

> Why are we using a fork of the tool though?

Because the upstream implementation contains bugs and its owner is not actively maintaining it.

BTW, I added this CI to other openssh-rust
repositories and so far it works pretty good.

It hasn't created any PR as no major release has been released yet for their dependencies.

**Comment by jonhoo** [comment]
Actually, how come we can't just use [dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates)?

**Comment by NobodyXu** [comment]
> Actually, how come we can't just use [dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates)?

Thanks, I didn't know it before.

I will closed this PR and would open another PR that uses dependabot.

**Pull request closed without merging**
