### PR TITLE
Fix `Session::control_socket` for future support of windows

### PR DESCRIPTION
**Pull request by NobodyXu**
Return `Option<&Path>` instead of `&Path` so that we can return `None`
on windows.

Signed-off-by: Jiahao XU <Jiahao_XU@outlook.com>

### CODE REVIEW

**Comment by jonhoo** [comment]
This change is [Reviewable](https://reviewable.io/reviews/openssh-rust/openssh/52)

**Comment by jonhoo** [comment]
How do you feel about making this function  `#[cfg(not(windows))]` instead, so signal that there is no control master on windows at compile time?

**Comment by NobodyXu** [comment]
> How do you feel about making this function `#[cfg(not(windows))]` instead, so signal that there is no control master on windows at compile time?

Yeah, I think using cfg here is fairly reasonable.

P.S., I am thinking of adding native ssh client implementation in the future, so that's why I propose to return an Option.

But maybe that will be something in the next breaking release, since I am still researching ssh negotiation.

**Comment by jonhoo** [comment]
I explicitly don't want to implement ssh in this crate as it means re-implementing far too much of the trusted path, so I'm okay with not making this `Option` and just making it `#[cfg(not(windows))]`. :)

**Comment by NobodyXu** [comment]
> I explicitly don't want to implement ssh in this crate as it means re-implementing far too much of the trusted path, so I'm okay with not making this `Option` and just making it `#[cfg(not(windows))]`. :)

Done!

**Review by jonhoo — APPROVED** [review]

**Pull request merged**
