### PR TITLE
Install `cargo-hack` on ci using `taiki/install-action`

### PR DESCRIPTION
**Pull request by NobodyXu**
Signed-off-by: Jiahao XU <Jiahao_XU@outlook.com>

### CODE REVIEW

**Comment by jonhoo** [comment]
This change is [Reviewable](https://reviewable.io/reviews/openssh-rust/openssh/73)

**Comment by jonhoo** [comment]
Looking at the [build logs](https://github.com/openssh-rust/openssh/actions/workflows/features.yml) it only seems to save 5-20s? We _should_ be getting most of the benefits from actions-rs/install already. I'm a little confused what value-add install-action provides, and why that change can't also be adopted into actions-rs/install?

**Comment by NobodyXu** [comment]
> Looking at the [build logs](https://github.com/openssh-rust/openssh/actions/workflows/features.yml) it only seems to save 5-20s? We _should_ be getting most of the benefits from actions-rs/install already.

The "use-tool-cache" support in actions-rs/install is disabled, so it would just call cargo install to compile it every time the CI run.

> I'm a little confused what value-add install-action provides, and why that change can't also be adopted into actions-rs/install?

taiki/install-action guarantees that no compilation is done.

It simply copies the precompiled binary.

**Comment by NobodyXu** [comment]
Another advantages of `taiki-e/install-action` always provides up-to-date `cargo-hack`, where using cache might end up using an out-dated version of `cargo-hack`.

**Review by jonhoo — APPROVED** [review]
Okay, fair enough. I still feel like this means that `actions-rs` should be fixed, but I'm also happy to use anything made by @taiki-e :)

**Pull request merged**
